api_secret_key = "AIzaSyCn3gPh1ACc1FWG8TsHPJUPL7iQFDZ65js"

[destination.motherduck.credentials]
database = "my_db"
password = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzaHVqb2VsODhAZ21haWwuY29tIiwibWRSZWdpb24iOiJhd3MtZXUtY2VudHJhbC0xIiwic2Vzc2lvbiI6ImFzaHVqb2VsODguZ21haWwuY29tIiwicGF0IjoiNi02TlFpMWljSzBSNWVPZzFhNTFWOThWSUxWTFJqV2wxc3R5ODFfeEswSSIsInVzZXJJZCI6Ijk4N2Q3ODhjLWNmMDEtNGNjMi04ZDRjLTJiNDVmOTcyNTM4NCIsImlzcyI6Im1kX3BhdCIsInJlYWRPbmx5IjpmYWxzZSwidG9rZW5UeXBlIjoicmVhZF93cml0ZSIsImlhdCI6MTc5MDAzODM1MH0.4mO5p8ZEATX5mmFK617bnUE-UZGB4Kx6A4OwWTktJMo"
